In [1]:
import math
import csv
from numpy import *  
import numpy as np
import pandas as pd  
#假設投資人分別在鴻海、中鋼、富邦金、台化分別投資了四百萬、三百萬、一百萬、兩百萬
#則風險值計算如下

In [2]:
from pandas_datareader import data as web
import datetime as dt
import yfinance as yf
yf.pdr_override()
start = dt.datetime(2018, 3, 1)
end = dt.datetime(2019, 8, 31)
stk1 = web.get_data_yahoo(['2317.tw'],start, end)
stk2 = web.get_data_yahoo(['2002.tw'],start, end)
stk3 = web.get_data_yahoo(['2881.tw'],start, end)
stk4 = web.get_data_yahoo(['1326.tw'],start, end)
stk1.to_csv(r'stk1.csv')
stk2.to_csv(r'stk2.csv')
stk3.to_csv(r'stk3.csv')
stk4.to_csv(r'stk4.csv')




[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [3]:
#將價格轉換為報酬率
with open('stk1.csv','r') as fin:
    with open('stk1b.csv','w', newline= '') as fout:
        csvreader = csv.reader(fin, delimiter=',')
        csvwriter = csv.writer(fout, delimiter=',')
        header = next(csvreader)
        csvwriter.writerow(header)
        spec = 100
        for row in csvreader:
            rtn = (float(row[4])-spec)/spec            
            spec = float(row[4])
            row[1]=rtn            
            csvwriter.writerow(row)
with open('stk2.csv','r') as fin:
    with open('stk2b.csv','w', newline= '') as fout:
        csvreader = csv.reader(fin, delimiter=',')
        csvwriter = csv.writer(fout, delimiter=',')
        header = next(csvreader)
        csvwriter.writerow(header)
        spec = 100
        for row in csvreader:
            rtn = (float(row[4])-spec)/spec            
            spec = float(row[4])
            row[1]=rtn            
            csvwriter.writerow(row)
with open('stk3.csv','r') as fin:
    with open('stk3b.csv','w', newline= '') as fout:
        csvreader = csv.reader(fin, delimiter=',')
        csvwriter = csv.writer(fout, delimiter=',')
        header = next(csvreader)
        csvwriter.writerow(header)
        spec = 100
        for row in csvreader:
            rtn = (float(row[4])-spec)/spec            
            spec = float(row[4])
            row[1]=rtn            
            csvwriter.writerow(row)
with open('stk4.csv','r') as fin:
    with open('stk4b.csv','w', newline= '') as fout:
        csvreader = csv.reader(fin, delimiter=',')
        csvwriter = csv.writer(fout, delimiter=',')
        header = next(csvreader)
        csvwriter.writerow(header)
        spec = 100
        for row in csvreader:
            rtn = (float(row[4])-spec)/spec            
            spec = float(row[4])
            row[1]=rtn            
            csvwriter.writerow(row)

In [4]:
#計算varcov var
df=pd.read_csv('stk1b.csv')
alt=array(df[['Date','Open']])
alt1 = alt.T[1]
df=pd.read_csv('stk2b.csv')
alt=array(df[['Date','Open']])
alt2 = alt.T[1]
df=pd.read_csv('stk3b.csv')
alt=array(df[['Date','Open']])
alt3 = alt.T[1]
df=pd.read_csv('stk4b.csv')
alt=array(df[['Date','Open']])
alt4 = alt.T[1]
Tm = np.vstack((alt1,alt2, alt3, alt4))
Tm = pd.DataFrame(Tm, dtype = np.float)
VarCov=np.cov(Tm)
weight = [[4e6, 3e6, 1e6, 2e6]]
wt = mat(weight).T
m1 = np.dot(weight, VarCov)
m2 = np.dot(m1, wt)
VAR1day99 = 2.326* m2[0,0]**.5

In [5]:
print("鴻海報酬平均",np.mean(alt1))
print("鴻海報酬標準差",np.std(alt1))
print("中鋼報酬平均",np.mean(alt2))
print("中鋼報酬標準差",np.std(alt2))
print("富邦金報酬平均",np.mean(alt3))
print("富邦金報酬標準差",np.std(alt3))
print("台化報酬平均",np.mean(alt4))
print("台化報酬標準差",np.std(alt4))
print("VC矩陣")
print(VarCov)
print("VaR =",VAR1day99)

鴻海報酬平均 -0.0006554249779989505
鴻海報酬標準差 0.017496454805634495
中鋼報酬平均 -0.002159448236246614
中鋼報酬標準差 0.0400961891316371
富邦金報酬平均 -0.0017308944906730506
富邦金報酬標準差 0.026727082386655596
台化報酬平均 -0.00023769128296645474
台化報酬標準差 0.014470413814713909
VC矩陣
[[ 3.06957795e-04 -1.56407900e-04 -6.90169654e-05  8.53658349e-05]
 [-1.56407900e-04  1.61207314e-03  1.01156330e-03 -7.30641517e-05]
 [-6.90169654e-05  1.01156330e-03  7.16278066e-04 -2.11198416e-05]
 [ 8.53658349e-05 -7.30641517e-05 -2.11198416e-05  2.09961878e-04]]
VaR = 353859.19890645694


In [15]:
m1

array([[ 860.32218311, 5076.02283285, 3432.660427  ,  521.07479952]])